"""birth date column back to date type

Revision ID: 1219b930dd5d
Revises: 9ccde5a5a579
Create Date: 2025-11-10 16:39:55.668590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1219b930dd5d'
down_revision: Union[str, Sequence[str], None] = '9ccde5a5a579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('birthDate', sa.Date(), nullable=False))
    op.drop_column('players', 'birthDateStr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('birthDateStr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('players', 'birthDate')
    # ### end Alembic commands ###
