"""initial migration

Revision ID: 157b425cbd03
Revises: 
Create Date: 2025-11-25 18:03:12.972176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157b425cbd03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('typeCode', sa.Integer(), nullable=False),
    sa.Column('typeDescKey', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('typeCode')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('franchiseID', sa.Integer(), nullable=True),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('triCode', sa.String(), nullable=False),
    sa.Column('metaDateTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('gameType', sa.Integer(), nullable=False),
    sa.Column('neutralSite', sa.Boolean(), nullable=False),
    sa.Column('gameDate', sa.Date(), nullable=False),
    sa.Column('defaultVenue', sa.String(), nullable=False),
    sa.Column('awayTeamID', sa.Integer(), nullable=False),
    sa.Column('awayTeamScore', sa.Integer(), nullable=False),
    sa.Column('homeTeamID', sa.Integer(), nullable=False),
    sa.Column('homeTeamScore', sa.Integer(), nullable=False),
    sa.Column('lastPeriodType', sa.String(), nullable=False),
    sa.Column('metaDateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['awayTeamID'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['homeTeamID'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_gameType'), 'games', ['gameType'], unique=False)
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('currentTeamID', sa.Integer(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('sweaterNumber', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('headshot', sa.String(), nullable=True),
    sa.Column('heightInInches', sa.Integer(), nullable=True),
    sa.Column('heightInCentimeters', sa.Integer(), nullable=True),
    sa.Column('weightInPounds', sa.Integer(), nullable=True),
    sa.Column('weightInKilograms', sa.Integer(), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=False),
    sa.Column('birthCountry', sa.String(), nullable=False),
    sa.Column('shootsCatches', sa.String(), nullable=False),
    sa.Column('draftYear', sa.Integer(), nullable=True),
    sa.Column('draftTeamAbbrev', sa.String(), nullable=True),
    sa.Column('draftRound', sa.Integer(), nullable=True),
    sa.Column('draftPickInRound', sa.Integer(), nullable=True),
    sa.Column('draftOverallPick', sa.Integer(), nullable=True),
    sa.Column('inHHOF', sa.Boolean(), nullable=True),
    sa.Column('metaDateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['currentTeamID'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('awards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('awardName', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('winningPlayerID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['winningPlayerID'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('awardName', 'season', name='awards_constraint')
    )
    op.create_index(op.f('ix_awards_season'), 'awards', ['season'], unique=False)
    op.create_table('events',
    sa.Column('eventID', sa.Integer(), nullable=False),
    sa.Column('gameID', sa.Integer(), nullable=False),
    sa.Column('timeInPeriodSec', sa.Integer(), nullable=False),
    sa.Column('awayScore', sa.Integer(), nullable=True),
    sa.Column('homeScore', sa.Integer(), nullable=True),
    sa.Column('awayGoalie', sa.Integer(), nullable=True),
    sa.Column('awaySkaters', sa.Integer(), nullable=True),
    sa.Column('homeGoalie', sa.Integer(), nullable=True),
    sa.Column('homeSkaters', sa.Integer(), nullable=True),
    sa.Column('homeTeamDefendingSide', sa.String(), nullable=True),
    sa.Column('typeCode', sa.Integer(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('periodType', sa.String(), nullable=True),
    sa.Column('eventOwnerTeamID', sa.Integer(), nullable=True),
    sa.Column('losingPlayerID', sa.Integer(), nullable=True),
    sa.Column('winningPlayerID', sa.Integer(), nullable=True),
    sa.Column('xCoord', sa.Float(), nullable=True),
    sa.Column('yCoord', sa.Float(), nullable=True),
    sa.Column('xStd', sa.Float(), nullable=True),
    sa.Column('yStd', sa.Float(), nullable=True),
    sa.Column('zoneCode', sa.String(), nullable=True),
    sa.Column('hittingPlayerID', sa.Integer(), nullable=True),
    sa.Column('hitteePlayerID', sa.Integer(), nullable=True),
    sa.Column('blockingPlayerID', sa.Integer(), nullable=True),
    sa.Column('shootingPlayerID', sa.Integer(), nullable=True),
    sa.Column('shotType', sa.String(), nullable=True),
    sa.Column('goalieInNetID', sa.Integer(), nullable=True),
    sa.Column('eventOwnerPlayerID', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('committedByPlayerID', sa.Integer(), nullable=True),
    sa.Column('drawnByPlayerID', sa.Integer(), nullable=True),
    sa.Column('scoringPlayerID', sa.Integer(), nullable=True),
    sa.Column('assist1PlayerID', sa.Integer(), nullable=True),
    sa.Column('assist2PlayerID', sa.Integer(), nullable=True),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('highlightClipSharingURL', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assist1PlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['assist2PlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['blockingPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['committedByPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['drawnByPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['eventOwnerPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['eventOwnerTeamID'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['gameID'], ['games.id'], ),
    sa.ForeignKeyConstraint(['goalieInNetID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['hitteePlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['hittingPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['losingPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['scoringPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['shootingPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['typeCode'], ['event_types.typeCode'], ),
    sa.ForeignKeyConstraint(['winningPlayerID'], ['players.id'], ),
    sa.PrimaryKeyConstraint('eventID', 'gameID')
    )
    op.create_index(op.f('ix_events_assist1PlayerID'), 'events', ['assist1PlayerID'], unique=False)
    op.create_index(op.f('ix_events_assist2PlayerID'), 'events', ['assist2PlayerID'], unique=False)
    op.create_index(op.f('ix_events_blockingPlayerID'), 'events', ['blockingPlayerID'], unique=False)
    op.create_index(op.f('ix_events_committedByPlayerID'), 'events', ['committedByPlayerID'], unique=False)
    op.create_index(op.f('ix_events_drawnByPlayerID'), 'events', ['drawnByPlayerID'], unique=False)
    op.create_index(op.f('ix_events_eventOwnerPlayerID'), 'events', ['eventOwnerPlayerID'], unique=False)
    op.create_index(op.f('ix_events_eventOwnerTeamID'), 'events', ['eventOwnerTeamID'], unique=False)
    op.create_index(op.f('ix_events_gameID'), 'events', ['gameID'], unique=False)
    op.create_index(op.f('ix_events_goalieInNetID'), 'events', ['goalieInNetID'], unique=False)
    op.create_index(op.f('ix_events_hitteePlayerID'), 'events', ['hitteePlayerID'], unique=False)
    op.create_index(op.f('ix_events_hittingPlayerID'), 'events', ['hittingPlayerID'], unique=False)
    op.create_index(op.f('ix_events_losingPlayerID'), 'events', ['losingPlayerID'], unique=False)
    op.create_index(op.f('ix_events_scoringPlayerID'), 'events', ['scoringPlayerID'], unique=False)
    op.create_index(op.f('ix_events_shootingPlayerID'), 'events', ['shootingPlayerID'], unique=False)
    op.create_index(op.f('ix_events_typeCode'), 'events', ['typeCode'], unique=False)
    op.create_index(op.f('ix_events_winningPlayerID'), 'events', ['winningPlayerID'], unique=False)
    op.create_table('goalie_appearances',
    sa.Column('playerID', sa.Integer(), nullable=False),
    sa.Column('gameID', sa.Integer(), nullable=False),
    sa.Column('teamID', sa.Integer(), nullable=False),
    sa.Column('evenStrengthSaves', sa.Integer(), nullable=False),
    sa.Column('evenStrengthShotsAgainst', sa.Integer(), nullable=False),
    sa.Column('powerPlaySaves', sa.Integer(), nullable=False),
    sa.Column('powerPlayShotsAgainst', sa.Integer(), nullable=False),
    sa.Column('shorthandedSaves', sa.Integer(), nullable=False),
    sa.Column('shorthandedShotsAgainst', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('shotsAgainst', sa.Integer(), nullable=False),
    sa.Column('toiSeconds', sa.Integer(), nullable=False),
    sa.Column('starter', sa.Boolean(), nullable=False),
    sa.Column('played', sa.Boolean(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gameID'], ['games.id'], ),
    sa.ForeignKeyConstraint(['playerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['teamID'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('playerID', 'gameID')
    )
    op.create_index(op.f('ix_goalie_appearances_gameID'), 'goalie_appearances', ['gameID'], unique=False)
    op.create_index(op.f('ix_goalie_appearances_playerID'), 'goalie_appearances', ['playerID'], unique=False)
    op.create_index(op.f('ix_goalie_appearances_teamID'), 'goalie_appearances', ['teamID'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gameID', sa.Integer(), nullable=False),
    sa.Column('playerID', sa.Integer(), nullable=False),
    sa.Column('teamID', sa.Integer(), nullable=False),
    sa.Column('durationSec', sa.Integer(), nullable=False),
    sa.Column('startTimeSec', sa.Integer(), nullable=False),
    sa.Column('endTimeSec', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('shiftNumber', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gameID'], ['games.id'], ),
    sa.ForeignKeyConstraint(['playerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['teamID'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_gameID'), 'shifts', ['gameID'], unique=False)
    op.create_index(op.f('ix_shifts_playerID'), 'shifts', ['playerID'], unique=False)
    op.create_index(op.f('ix_shifts_teamID'), 'shifts', ['teamID'], unique=False)
    op.create_table('skater_appearances',
    sa.Column('appearanceID', sa.Integer(), nullable=False),
    sa.Column('playerID', sa.Integer(), nullable=False),
    sa.Column('teamID', sa.Integer(), nullable=False),
    sa.Column('gameID', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('powerPlayGoals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('plusMinus', sa.Integer(), nullable=False),
    sa.Column('pim', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('sog', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('giveaways', sa.Integer(), nullable=False),
    sa.Column('takeaways', sa.Integer(), nullable=False),
    sa.Column('toiSeconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gameID'], ['games.id'], ),
    sa.ForeignKeyConstraint(['playerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['teamID'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('appearanceID')
    )
    op.create_index(op.f('ix_skater_appearances_gameID'), 'skater_appearances', ['gameID'], unique=False)
    op.create_index(op.f('ix_skater_appearances_playerID'), 'skater_appearances', ['playerID'], unique=False)
    op.create_index(op.f('ix_skater_appearances_teamID'), 'skater_appearances', ['teamID'], unique=False)
    op.create_table('split_shifts',
    sa.Column('shiftID', sa.Integer(), nullable=False),
    sa.Column('split', sa.Integer(), nullable=False),
    sa.Column('teamID', sa.Integer(), nullable=False),
    sa.Column('playerID', sa.Integer(), nullable=False),
    sa.Column('gameID', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('startTimeSec', sa.Integer(), nullable=False),
    sa.Column('endTimeSec', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('attackingSkaters', sa.Integer(), nullable=False),
    sa.Column('defendingSkaters', sa.Integer(), nullable=False),
    sa.Column('attackingGoalie', sa.Boolean(), nullable=False),
    sa.Column('defendingGoalie', sa.Boolean(), nullable=False),
    sa.Column('goalsFor', sa.Integer(), nullable=False),
    sa.Column('goalsAgainst', sa.Integer(), nullable=False),
    sa.Column('sogFor', sa.Integer(), nullable=False),
    sa.Column('sogAgainst', sa.Integer(), nullable=False),
    sa.Column('fenwickFor', sa.Integer(), nullable=False),
    sa.Column('fenwickAgainst', sa.Integer(), nullable=False),
    sa.Column('corsiFor', sa.Integer(), nullable=False),
    sa.Column('corsiAgainst', sa.Integer(), nullable=False),
    sa.Column('xgFor', sa.Float(), nullable=False),
    sa.Column('xgAgainst', sa.Float(), nullable=False),
    sa.Column('dZoneStarts', sa.Integer(), nullable=False),
    sa.Column('nZoneStarts', sa.Integer(), nullable=False),
    sa.Column('oZoneStarts', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gameID'], ['games.id'], ),
    sa.ForeignKeyConstraint(['playerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['teamID'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('shiftID', 'split')
    )
    op.create_index(op.f('ix_split_shifts_gameID'), 'split_shifts', ['gameID'], unique=False)
    op.create_index(op.f('ix_split_shifts_playerID'), 'split_shifts', ['playerID'], unique=False)
    op.create_index(op.f('ix_split_shifts_teamID'), 'split_shifts', ['teamID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_split_shifts_teamID'), table_name='split_shifts')
    op.drop_index(op.f('ix_split_shifts_playerID'), table_name='split_shifts')
    op.drop_index(op.f('ix_split_shifts_gameID'), table_name='split_shifts')
    op.drop_table('split_shifts')
    op.drop_index(op.f('ix_skater_appearances_teamID'), table_name='skater_appearances')
    op.drop_index(op.f('ix_skater_appearances_playerID'), table_name='skater_appearances')
    op.drop_index(op.f('ix_skater_appearances_gameID'), table_name='skater_appearances')
    op.drop_table('skater_appearances')
    op.drop_index(op.f('ix_shifts_teamID'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_playerID'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_gameID'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_goalie_appearances_teamID'), table_name='goalie_appearances')
    op.drop_index(op.f('ix_goalie_appearances_playerID'), table_name='goalie_appearances')
    op.drop_index(op.f('ix_goalie_appearances_gameID'), table_name='goalie_appearances')
    op.drop_table('goalie_appearances')
    op.drop_index(op.f('ix_events_winningPlayerID'), table_name='events')
    op.drop_index(op.f('ix_events_typeCode'), table_name='events')
    op.drop_index(op.f('ix_events_shootingPlayerID'), table_name='events')
    op.drop_index(op.f('ix_events_scoringPlayerID'), table_name='events')
    op.drop_index(op.f('ix_events_losingPlayerID'), table_name='events')
    op.drop_index(op.f('ix_events_hittingPlayerID'), table_name='events')
    op.drop_index(op.f('ix_events_hitteePlayerID'), table_name='events')
    op.drop_index(op.f('ix_events_goalieInNetID'), table_name='events')
    op.drop_index(op.f('ix_events_gameID'), table_name='events')
    op.drop_index(op.f('ix_events_eventOwnerTeamID'), table_name='events')
    op.drop_index(op.f('ix_events_eventOwnerPlayerID'), table_name='events')
    op.drop_index(op.f('ix_events_drawnByPlayerID'), table_name='events')
    op.drop_index(op.f('ix_events_committedByPlayerID'), table_name='events')
    op.drop_index(op.f('ix_events_blockingPlayerID'), table_name='events')
    op.drop_index(op.f('ix_events_assist2PlayerID'), table_name='events')
    op.drop_index(op.f('ix_events_assist1PlayerID'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_awards_season'), table_name='awards')
    op.drop_table('awards')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_index(op.f('ix_games_gameType'), table_name='games')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('event_types')
    # ### end Alembic commands ###
