"""remove game states, team place names

Revision ID: 1a069127fbe7
Revises: bf4ad5204aa1
Create Date: 2025-11-13 18:52:10.712690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a069127fbe7'
down_revision: Union[str, Sequence[str], None] = 'bf4ad5204aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'gameState')
    op.drop_column('games', 'gameScheduleState')
    op.drop_column('teams', 'placeName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('placeName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('gameScheduleState', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('gameState', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
