"""add highlight link

Revision ID: 48b914dff02d
Revises: 99ec86ab0cfd
Create Date: 2025-11-17 18:58:41.909759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b914dff02d'
down_revision: Union[str, Sequence[str], None] = '99ec86ab0cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('highlightClipSharingURL', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'highlightClipSharingURL')
    # ### end Alembic commands ###
