"""remove awards

Revision ID: 532770a98678
Revises: 4c9378650e51
Create Date: 2025-11-11 17:58:57.719254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '532770a98678'
down_revision: Union[str, Sequence[str], None] = '4c9378650e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_awards_season'), table_name='awards')
    op.drop_table('awards')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('awardName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('winningPlayerID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['winningPlayerID'], ['players.id'], name=op.f('awards_winningPlayerID_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('awards_pkey'))
    )
    op.create_index(op.f('ix_awards_season'), 'awards', ['season'], unique=False)
    # ### end Alembic commands ###
