"""add std coords and scores to events

Revision ID: 99ec86ab0cfd
Revises: 1a069127fbe7
Create Date: 2025-11-13 21:09:01.816552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ec86ab0cfd'
down_revision: Union[str, Sequence[str], None] = '1a069127fbe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('awayScore', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('homeScore', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('xStd', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('yStd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'yStd')
    op.drop_column('events', 'xStd')
    op.drop_column('events', 'homeScore')
    op.drop_column('events', 'awayScore')
    # ### end Alembic commands ###
