"""birth date fix

Revision ID: 9ccde5a5a579
Revises: 311967539aa0
Create Date: 2025-11-10 16:28:07.773514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ccde5a5a579'
down_revision: Union[str, Sequence[str], None] = '311967539aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('birthDateStr', sa.String(), nullable=False))
    op.drop_column('players', 'birthDate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('birthDate', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('players', 'birthDateStr')
    # ### end Alembic commands ###
