"""new awards table with constraint

Revision ID: bf4ad5204aa1
Revises: 532770a98678
Create Date: 2025-11-11 18:07:34.372131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4ad5204aa1'
down_revision: Union[str, Sequence[str], None] = '532770a98678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('awardName', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('winningPlayerID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['winningPlayerID'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('awardName', 'season', name='awards_constraint')
    )
    op.create_index(op.f('ix_awards_season'), 'awards', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_awards_season'), table_name='awards')
    op.drop_table('awards')
    # ### end Alembic commands ###
