"""fix event schema

Revision ID: c07eed2edc96
Revises: 48b914dff02d
Create Date: 2025-11-17 19:01:54.858852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07eed2edc96'
down_revision: Union[str, Sequence[str], None] = '48b914dff02d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'timeInPeriodSec',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'homeTeamDefendingSide',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'period',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'losingPlayerID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'winningPlayerID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_events_playerID'), table_name='events')
    op.drop_constraint(op.f('events_playerID_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'playerID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('playerID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('events_playerID_fkey'), 'events', 'players', ['playerID'], ['id'])
    op.create_index(op.f('ix_events_playerID'), 'events', ['playerID'], unique=False)
    op.alter_column('events', 'winningPlayerID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'losingPlayerID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'period',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'homeTeamDefendingSide',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'timeInPeriodSec',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
