"""awards delete cascade

Revision ID: c69063db464f
Revises: b51af41c2e02
Create Date: 2025-11-11 11:53:18.697178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69063db464f'
down_revision: Union[str, Sequence[str], None] = 'b51af41c2e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'fullNameFR')
    op.drop_column('teams', 'commonNameFR')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('commonNameFR', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('fullNameFR', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
