"""add score to SplitShift

Revision ID: ccafcba587ea
Revises: c07eed2edc96
Create Date: 2025-11-20 20:44:49.915095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccafcba587ea'
down_revision: Union[str, Sequence[str], None] = 'c07eed2edc96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('split_shifts', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('split_shifts', sa.Column('score', sa.Integer(), nullable=False))
    op.drop_column('split_shifts', 'splitDuration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('split_shifts', sa.Column('splitDuration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('split_shifts', 'score')
    op.drop_column('split_shifts', 'duration')
    # ### end Alembic commands ###
