"""Fixed event fields

Revision ID: 075da4675bc6
Revises: d3c1c2b83042
Create Date: 2025-01-17 11:52:45.172623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075da4675bc6'
down_revision = 'd3c1c2b83042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('timeInPeriodMin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeInPeriodMin', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
