"""First migration

Revision ID: 5aaed4cad1d4
Revises: 
Create Date: 2025-01-13 22:28:27.705272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aaed4cad1d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('typeCode', sa.Integer(), nullable=False),
    sa.Column('typeDescKey', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('typeCode')
    )
    op.create_table('game_types',
    sa.Column('typeCode', sa.Integer(), nullable=False),
    sa.Column('typeDescKey', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('typeCode')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('commonName', sa.String(), nullable=False),
    sa.Column('placeName', sa.String(), nullable=False),
    sa.Column('metaDateTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Integer(), nullable=False),
    sa.Column('currentTeamID', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('sweaterNumber', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('headshot', sa.String(), nullable=True),
    sa.Column('heroImage', sa.String(), nullable=True),
    sa.Column('heightInInches', sa.Integer(), nullable=True),
    sa.Column('heightInCentimeters', sa.Integer(), nullable=True),
    sa.Column('weightInPounds', sa.Integer(), nullable=True),
    sa.Column('weightInKilograms', sa.Integer(), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=False),
    sa.Column('birthCity', sa.String(), nullable=True),
    sa.Column('birthCountry', sa.String(), nullable=True),
    sa.Column('shootsCatches', sa.String(), nullable=False),
    sa.Column('draftYear', sa.Integer(), nullable=True),
    sa.Column('draftTeamAbbrev', sa.String(), nullable=True),
    sa.Column('draftRound', sa.Integer(), nullable=True),
    sa.Column('draftPickInRound', sa.Integer(), nullable=True),
    sa.Column('draftOverallPick', sa.Integer(), nullable=True),
    sa.Column('inHHOF', sa.Integer(), nullable=True),
    sa.Column('metaDateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['currentTeamID'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('gameType', sa.Integer(), nullable=False),
    sa.Column('neutralSite', sa.Integer(), nullable=True),
    sa.Column('startTimeUTC', sa.DateTime(), nullable=False),
    sa.Column('venueUTCOffset', sa.Integer(), nullable=False),
    sa.Column('gameState', sa.String(), nullable=False),
    sa.Column('gameScheduleState', sa.String(), nullable=False),
    sa.Column('defaultVenue', sa.String(), nullable=False),
    sa.Column('awayTeamID', sa.Integer(), nullable=False),
    sa.Column('awayTeamScore', sa.Integer(), nullable=False),
    sa.Column('homeTeamID', sa.Integer(), nullable=False),
    sa.Column('homeTeamScore', sa.Integer(), nullable=False),
    sa.Column('maxRegulationPeriods', sa.Integer(), nullable=False),
    sa.Column('lastPeriodType', sa.String(), nullable=False),
    sa.Column('winningGoalieID', sa.Integer(), nullable=False),
    sa.Column('winningGoalscorerID', sa.Integer(), nullable=True),
    sa.Column('metaDateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['awayTeamID'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['gameType'], ['game_types.typeCode'], ),
    sa.ForeignKeyConstraint(['homeTeamID'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['winningGoalieID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winningGoalscorerID'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeInPeriodMin', sa.Integer(), nullable=False),
    sa.Column('timeInPeriodSec', sa.Integer(), nullable=False),
    sa.Column('awayGoalie', sa.Integer(), nullable=False),
    sa.Column('awaySkaters', sa.Integer(), nullable=False),
    sa.Column('homeGoalie', sa.Integer(), nullable=False),
    sa.Column('homeSkaters', sa.Integer(), nullable=False),
    sa.Column('homeTeamDefendingSide', sa.String(), nullable=False),
    sa.Column('typeCode', sa.Integer(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('periodType', sa.String(), nullable=False),
    sa.Column('eventOwnerTeamID', sa.Integer(), nullable=True),
    sa.Column('losingPlayerID', sa.Integer(), nullable=True),
    sa.Column('winningPlayerID', sa.Integer(), nullable=True),
    sa.Column('xCoord', sa.Float(), nullable=True),
    sa.Column('yCoord', sa.Float(), nullable=True),
    sa.Column('zoneCode', sa.String(), nullable=True),
    sa.Column('hittingPlayerID', sa.Integer(), nullable=True),
    sa.Column('hitteePlayerID', sa.Integer(), nullable=True),
    sa.Column('blockingPlayerID', sa.Integer(), nullable=True),
    sa.Column('shootingPlayerID', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('shotType', sa.String(), nullable=True),
    sa.Column('goalieInNetID', sa.Integer(), nullable=True),
    sa.Column('eventOwnerPlayerID', sa.Integer(), nullable=True),
    sa.Column('penaltyDuration', sa.Integer(), nullable=True),
    sa.Column('committedByPlayerID', sa.Integer(), nullable=True),
    sa.Column('drawnByPlayerID', sa.Integer(), nullable=True),
    sa.Column('scoringPlayerID', sa.Integer(), nullable=True),
    sa.Column('assist1PlayerID', sa.Integer(), nullable=True),
    sa.Column('assist2PlayerID', sa.Integer(), nullable=True),
    sa.Column('gameID', sa.Integer(), nullable=False),
    sa.Column('metaDateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assist1PlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['assist2PlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['blockingPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['committedByPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['drawnByPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['eventOwnerPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['eventOwnerTeamID'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['gameID'], ['games.id'], ),
    sa.ForeignKeyConstraint(['goalieInNetID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['hitteePlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['hittingPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['losingPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['scoringPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['shootingPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['typeCode'], ['event_types.typeCode'], ),
    sa.ForeignKeyConstraint(['winningPlayerID'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('games')
    op.drop_table('players')
    op.drop_table('teams')
    op.drop_table('game_types')
    op.drop_table('event_types')
    # ### end Alembic commands ###
