"""games and game_types tables

Revision ID: 6104f994567e
Revises: b5254098019b
Create Date: 2025-01-12 17:28:48.100391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6104f994567e'
down_revision = 'b5254098019b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_types',
    sa.Column('typeCode', sa.Integer(), nullable=False),
    sa.Column('typeDescKey', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('typeCode')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('gameType', sa.Integer(), nullable=False),
    sa.Column('inHHOF', sa.Integer(), nullable=True),
    sa.Column('startTimeUTC', sa.DateTime(), nullable=False),
    sa.Column('venueUTCOffset', sa.Integer(), nullable=False),
    sa.Column('gameState', sa.String(), nullable=False),
    sa.Column('gameScheduleState', sa.String(), nullable=False),
    sa.Column('defaultVenue', sa.String(), nullable=False),
    sa.Column('awayTeamID', sa.Integer(), nullable=False),
    sa.Column('awayTeamScore', sa.Integer(), nullable=False),
    sa.Column('homeTeamID', sa.Integer(), nullable=False),
    sa.Column('homeTeamScore', sa.Integer(), nullable=False),
    sa.Column('maxRegulationPeriod', sa.Integer(), nullable=False),
    sa.Column('lastPeriodType', sa.String(), nullable=False),
    sa.Column('winningGoalieID', sa.Integer(), nullable=False),
    sa.Column('winningGoalscorerID', sa.Integer(), nullable=True),
    sa.Column('metaDateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['awayTeamID'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['gameType'], ['game_types.typeCode'], ),
    sa.ForeignKeyConstraint(['homeTeamID'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['winningGoalieID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winningGoalscorerID'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('game_types')
    # ### end Alembic commands ###
