"""remvoed player-game relationship

Revision ID: 7bd224067213
Revises: 8a94a5f60ee1
Create Date: 2025-01-18 15:41:09.663395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd224067213'
down_revision = '8a94a5f60ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_teams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_teams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('placeName', sa.VARCHAR(), nullable=False),
    sa.Column('commonName', sa.VARCHAR(), nullable=False),
    sa.Column('fullName', sa.VARCHAR(), nullable=False),
    sa.Column('metaDateTime', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
