"""Fixed team model

Revision ID: 8a94a5f60ee1
Revises: 075da4675bc6
Create Date: 2025-01-17 17:58:21.053357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a94a5f60ee1'
down_revision = '075da4675bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('franchiseID', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('triCode', sa.String(), nullable=False))
        batch_op.drop_column('commonName')
        batch_op.drop_column('placeName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placeName', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('commonName', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('triCode')
        batch_op.drop_column('franchiseID')

    # ### end Alembic commands ###
