"""added shifts table

Revision ID: 901d271f693c
Revises: 5aaed4cad1d4
Create Date: 2025-01-14 15:36:32.425689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901d271f693c'
down_revision = '5aaed4cad1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('durationSec', sa.Integer(), nullable=False),
    sa.Column('startTimeMin', sa.Integer(), nullable=False),
    sa.Column('startTimeSec', sa.Integer(), nullable=False),
    sa.Column('endTimeMin', sa.Integer(), nullable=False),
    sa.Column('endTimeSec', sa.Integer(), nullable=False),
    sa.Column('eventNumber', sa.Integer(), nullable=False),
    sa.Column('gameID', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('playerID', sa.Integer(), nullable=False),
    sa.Column('shiftNumber', sa.Integer(), nullable=False),
    sa.Column('teamID', sa.Integer(), nullable=False),
    sa.Column('metaDateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gameID'], ['games.id'], ),
    sa.ForeignKeyConstraint(['playerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['teamID'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shifts')
    # ### end Alembic commands ###
