"""events and event_types tables

Revision ID: a3dde30da919
Revises: 6104f994567e
Create Date: 2025-01-12 17:43:33.924505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3dde30da919'
down_revision = '6104f994567e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('typeCode', sa.Integer(), nullable=False),
    sa.Column('typeDescKey', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('typeCode')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeInPeriod', sa.String(), nullable=False),
    sa.Column('timeRemaining', sa.String(), nullable=False),
    sa.Column('awayGoalie', sa.Integer(), nullable=False),
    sa.Column('awaySkaters', sa.Integer(), nullable=False),
    sa.Column('homeGoalie', sa.Integer(), nullable=False),
    sa.Column('homeSkaters', sa.Integer(), nullable=False),
    sa.Column('homeTeamDefendingSide', sa.String(), nullable=False),
    sa.Column('typeCode', sa.Integer(), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('periodType', sa.Integer(), nullable=False),
    sa.Column('eventOwnerTeamID', sa.Integer(), nullable=True),
    sa.Column('losingPlayerID', sa.Integer(), nullable=True),
    sa.Column('winningPlayerID', sa.Integer(), nullable=True),
    sa.Column('xCoord', sa.Float(), nullable=True),
    sa.Column('yCoord', sa.Float(), nullable=True),
    sa.Column('zoneCode', sa.String(), nullable=True),
    sa.Column('hittingPlayerID', sa.Integer(), nullable=True),
    sa.Column('hitteePlayerID', sa.Integer(), nullable=True),
    sa.Column('blockingPlayerID', sa.Integer(), nullable=True),
    sa.Column('shootingPlayerID', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('shotType', sa.String(), nullable=True),
    sa.Column('goalieInNetID', sa.Integer(), nullable=True),
    sa.Column('eventOwnerPlayerID', sa.Integer(), nullable=True),
    sa.Column('penaltyDuration', sa.String(), nullable=True),
    sa.Column('committedByPlayerID', sa.Integer(), nullable=True),
    sa.Column('drawnByPlayerID', sa.Integer(), nullable=True),
    sa.Column('scoringPlayerID', sa.Integer(), nullable=True),
    sa.Column('assist1PlayerID', sa.Integer(), nullable=True),
    sa.Column('assist2PlayerID', sa.Integer(), nullable=True),
    sa.Column('gameID', sa.Integer(), nullable=False),
    sa.Column('metaDateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assist1PlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['assist2PlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['blockingPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['committedByPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['drawnByPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['eventOwnerPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['eventOwnerTeamID'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['gameID'], ['games.id'], ),
    sa.ForeignKeyConstraint(['goalieInNetID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['hitteePlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['hittingPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['losingPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['scoringPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['shootingPlayerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['typeCode'], ['event_types.typeCode'], ),
    sa.ForeignKeyConstraint(['winningPlayerID'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('event_types')
    # ### end Alembic commands ###
