"""players table

Revision ID: b5254098019b
Revises: f2517612fc71
Create Date: 2025-01-12 17:05:42.034516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5254098019b'
down_revision = 'f2517612fc71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Integer(), nullable=False),
    sa.Column('currentTeamID', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('sweaterNumber', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('headshot', sa.String(), nullable=False),
    sa.Column('heroImage', sa.String(), nullable=False),
    sa.Column('heightInInches', sa.Integer(), nullable=True),
    sa.Column('heightInCentimeters', sa.Integer(), nullable=True),
    sa.Column('weightInPounds', sa.Integer(), nullable=True),
    sa.Column('weightInKilograms', sa.Integer(), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=False),
    sa.Column('birthCity', sa.String(), nullable=True),
    sa.Column('birthCountry', sa.String(), nullable=True),
    sa.Column('shootsCatches', sa.String(), nullable=False),
    sa.Column('draftYear', sa.Integer(), nullable=True),
    sa.Column('draftTeamAbbrev', sa.String(), nullable=True),
    sa.Column('draftRound', sa.Integer(), nullable=True),
    sa.Column('draftPickInRound', sa.Integer(), nullable=True),
    sa.Column('draftOverallPick', sa.String(), nullable=True),
    sa.Column('inHHOF', sa.Integer(), nullable=False),
    sa.Column('metaDateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['currentTeamID'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
