"""Added player_games table

Revision ID: d3c1c2b83042
Revises: a22e38588a5c
Create Date: 2025-01-16 18:07:21.337889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c1c2b83042'
down_revision = 'a22e38588a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_games',
    sa.Column('gameID', sa.Integer(), nullable=False),
    sa.Column('teamID', sa.Integer(), nullable=False),
    sa.Column('playerID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gameID'], ['games.id'], ),
    sa.ForeignKeyConstraint(['playerID'], ['players.id'], ),
    sa.ForeignKeyConstraint(['teamID'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('gameID', 'teamID', 'playerID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_games')
    # ### end Alembic commands ###
